Blog post about comparison `0.0` and `-0.0`
objectionary/news.eolang.org pull request #46
Opened 2023-10-15 14:43 UTC by c71n93

Closes #43

2023-10-15 14:48 UTC, c71n93 commented
@maxonfjvipon could you check this blog post, please. I left the section `Conclusion` unfinished, because I don't know the answer to the questions I left there yet.

2023-10-31 16:13 UTC, c71n93 commented
@maxonfjvipon could you check this, please?

2023-11-01 12:01 UTC, maxonfjvipon requested changes
@c71n93 Good one! I like it, just a few comments from my side

2023-11-01 12:01 UTC, maxonfjvipon commented on _posts/2023/10/2023-10-20-comparison-of-floating-zeros.md
> +In order for the floating-point comparison in EO to comply with the standard, we have changed the behavior of the `eq`
@c71n93 I would add here that we didn't introduce atoms for `eq` and still compare floats bitwise but added special cases for zeros

2023-11-02 15:01 UTC, c71n93 commented
@maxonfjvipon I resolved your comments, could you check please?

2023-11-02 18:41 UTC, maxonfjvipon requested changes
@c71n93 please change date in the name of the file and I think it good to go

2023-11-02 19:09 UTC, c71n93 commented
@maxonfjvipon done

2023-11-02 20:38 UTC, maxonfjvipon approved these changes
@c71n93 good one, thanks

2023-11-03 11:19 UTC, c71n93 commented
@yegor256 could you check this one, please?

2023-11-03 12:12 UTC, yegor256 commented
@rultor merge

2023-11-03 12:15 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/36142-1792330881)

2023-11-03 12:16 UTC, merged

2023-11-03 12:18 UTC, rultor commented
> @rultor merge

@yegor256 Done! FYI, the full log is [here](https://www.rultor.com/t/36142-1792330881) (took me 3min)